#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	1) Network interface DNS mapping server resolv.conf
#			2) Restart networking to grab the new ip from /etc/networking/interfaces 			
### END INIT INFO

start_func() {
	ifdown -a
	ifup -a

	tmp=`grep -i nameserver /etc/resolv.conf`
	if [ "$tmp" = "" ] ; then
      		  sudo echo nameserver 192.168.2.1 >> /etc/resolv.conf
     		  sudo echo nameserver 8.8.8.8 >> /etc/resolv.conf        
	fi

}

#export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	start_func
	;;
  stop)
	;;

esac

exit 0

